# Generated by Django 3.2 on 2022-01-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='profile',
        ),
    ]
