# Generated by Django 3.2 on 2022-01-05 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0003_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
