# Generated by Django 3.2 on 2022-01-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0004_alter_project_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
